=== WallyS02/HiH-project/index.dtd
<!ELEMENT guitarists (guitarist+)>
<!ELEMENT guitarist (name, surname, lefthanded*, img, band, guitars, wikilink)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT surname (#PCDATA)>
<!ELEMENT img (#PCDATA)>
<!ELEMENT band (bandname, bandmembers, yearsactive, albums)>
<!ELEMENT guitars (guitar+)>
<!ELEMENT wikilink (#PCDATA)>
<!ELEMENT guitar (nameguitar, date, brand)>
<!ELEMENT nameguitar (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT brand (#PCDATA)>
<!ELEMENT bandname (#PCDATA)>
<!ELEMENT bandmembers (#PCDATA)>
<!ELEMENT yearsactive (#PCDATA)>
<!ELEMENT albums (album+)>
<!ELEMENT album (song+)>
<!ELEMENT song ((songname, length)|key)>
<!ELEMENT songname (#PCDATA)>
<!ELEMENT length (#PCDATA)>
<!ELEMENT key (#PCDATA)>
<!ELEMENT lefthanded (#PCDATA)>

<!ATTLIST guitarist n (1|2|3) #REQUIRED>
<!ATTLIST album kindone CDATA #IMPLIED>
<!ATTLIST album kindtwo CDATA #IMPLIED>
<!ATTLIST album kindthree CDATA #IMPLIED>
<!ATTLIST album heavy CDATA #IMPLIED>
<!ATTLIST album masterpiece CDATA #IMPLIED>
<!ATTLIST album iconic CDATA "%encjaparam1;">
<!ATTLIST guitar iconic CDATA #IMPLIED>
<!ATTLIST guitar id CDATA "%encjaparam2;">
<!ATTLIST img source CDATA #REQUIRED>
<!ATTLIST wikilink source CDATA #REQUIRED>

<!ENTITY encja "yes">
<!ENTITY % encjaparam1 "yes">
<!ENTITY % encjaparam2 "(1|2)">

=== WallyS02/HiH-project/index_doDTD.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE guitarists SYSTEM "index.dtd">
<guitarists>
	<guitarist n="1">
		<name>Tony</name>
		<surname>Iommi</surname>
		<lefthanded>&encja;</lefthanded>
		<img source="img/iommi.jpg"></img>
		<band>
			<bandname>Black Sabbath</bandname>
			<bandmembers>Iommi Ward Butler Osbourne</bandmembers>
			<yearsactive>49</yearsactive>
			<albums>
				<album kindone="Black Sabbath">
					<song>
						<songname>Black Sabbath</songname>
						<length>6</length>
					</song>
					<song>
						<songname>NIB</songname>
						<length>6</length>
					</song>
					<song>
						<songname>The Wizard</songname>
						<length>4</length>
					</song>
				</album>
				<album kindone="Paranoid">
					<song>
						<songname>Paranoid</songname>
						<length>3</length>
					</song>
					<song>
						<songname>War Pigs</songname>
						<length>8</length>
					</song>
					<song>
						<songname>Planet Caravan</songname>
						<length>4</length>
					</song>
				</album>
				<album kindone="Master of Reality" heavy="yes">
					<song>
						<songname>Sweet leaf</songname>
						<length>5</length>
					</song>
					<song>
						<songname>Solitude</songname>
						<length>5</length>
					</song>
					<song>
						<songname>Into the void</songname>
						<length>6</length>
					</song>
				</album>
			</albums>
		</band>
		<guitars>
			<guitar id="1" iconic="yes">
				<nameguitar>SG Special “Monkey”</nameguitar>
				<date>1965</date>
				<brand>Gibson</brand>
			</guitar>
			<guitar id="2">
				<nameguitar>SG “The Old Boy”</nameguitar>
				<date>1975</date>
				<brand>Jaydee</brand>
			</guitar>
		</guitars>
		<wikilink source="https://pl.wikipedia.org/wiki/Tony_Iommi">Tony Iommi Wiki</wikilink>
	</guitarist>

	<guitarist n="2">
		<name>David</name>
		<surname>Gilmour</surname>
		<img source="img/gilmour.jpg"></img>
		<band>
			<bandname>Pink Floyd</bandname>
			<bandmembers>Gilmour Wright Waters Mason</bandmembers>
			<yearsactive>forty nine years</yearsactive>
			<albums>
				<album kindtwo="The Dark Side of the Moon" masterpiece="yes">
					<song>
						<songname>Time</songname>
						<length>7</length>
					</song>
					<song>
						<songname>Money</songname>
						<length>6</length>
					</song>
					<song>
						<songname>Breathe</songname>
						<length>4</length>
					</song>
				</album>
				<album kindtwo="The Wall">
					<song>
						<songname>Young Lust</songname>
						<length>3</length>
					</song>
					<song>
						<songname>Is there anybody out there?</songname>
						<length>3</length>
					</song>
					<song>
						<songname>Another Brick in the Wall, Part 2</songname>
						<length>4</length>
					</song>
				</album>
				<album kindtwo="The Division Bell">
					<song>
						<songname>Marooned</songname>
						<length>5</length>
					</song>
					<song>
						<songname>Keep Talking</songname>
						<length>6</length>
					</song>
					<song>
						<songname>High Hopes</songname>
						<length>9</length>
					</song>
				</album>
			</albums>
		</band>
		<guitars>
			<guitar id="1" iconic="yes">
				<nameguitar>Stratocaster</nameguitar>
				<date>1969</date>
				<brand>Fender</brand>
			</guitar>
			<guitar id="2">
				<nameguitar>24-fret Guitar</nameguitar>
				<date>1970</date>
				<brand>Bill Lewis</brand>
			</guitar>
		</guitars>
		<wikilink source="https://pl.wikipedia.org/wiki/David_Gilmour">David Gilmour Wiki</wikilink>
	</guitarist>

	<guitarist n="3">
		<name>Jimi</name>
		<surname>Hendrix</surname>
		<lefthanded>&encja;</lefthanded>
		<img source="img/hendrix.jpg"></img>
		<band>
			<bandname>The Jimi Hendrix Experience</bandname>
			<bandmembers>Hendrix Redding Mitchell</bandmembers>
			<yearsactive>4</yearsactive>
			<albums>
				<album kindthree="Are you experienced">
					<song>
						<songname>Foxy Lady</songname>
						<length>3</length>
					</song>
					<song>
						<songname>Purple Haze</songname>
						<length>3</length>
					</song>
					<song>
						<songname>The Wind Cries Mary</songname>
						<length>3</length>
					</song>
				</album>
				<album kindthree="Axis: Bold as Love" iconic="yes">
					<song>
						<songname>Spanish Castle Magic</songname>
						<length>3</length>
					</song>
					<song>
						<songname>Little Wing</songname>
						<length>2</length>
					</song>
					<song>
						<songname>Castles Made of Sand</songname>
						<length>3</length>
					</song>
				</album>
				<album kindthree="Electric Layland">
					<song>
						<songname>Crosstown Traffic</songname>
						<length>2</length>
					</song>
					<song>
						<songname>All along the watchtower</songname>
						<length>4</length>
					</song>
					<song>
						<songname>Voodoo Child (Slight Return)</songname>
						<length>5</length>
					</song>
				</album>
			</albums>
		</band>
		<guitars>
			<guitar id="1">
				<nameguitar>Flying V</nameguitar>
				<date>1958</date>
				<brand>Gibson</brand>
			</guitar>
			<guitar id="2" iconic="yes">
				<nameguitar>Classic Series Stratocaster</nameguitar>
				<date>1960</date>
				<brand>Fender</brand>
			</guitar>
		</guitars>
		<wikilink source="https://pl.wikipedia.org/wiki/Jimi_Hendrix">Jimi Hendrix Wiki</wikilink>
	</guitarist>
</guitarists>
